#! perl
use warnings;
use strict;
use DBI;

use Mojolicious::Lite;
use Mojo::File qw(curfile);
my $conf = curfile->dirname->path('../my_app.json');
my $config = plugin 'JSONConfig' => { file => $conf };
use Env qw(DIRT_DB_CONSTRING DIRT_DB_USER DIRT_DB_PASS);
$config->{mssql}->{dbstring} = $DIRT_DB_CONSTRING if $DIRT_DB_CONSTRING;
$config->{mssql}->{username} = $DIRT_DB_USER if $DIRT_DB_USER;
$config->{mssql}->{password} = $DIRT_DB_PASS if $DIRT_DB_PASS;

#my $dbh = DBI->connect("dbi:ODBC:Driver=ODBC Driver 18 for SQL Server;Server=localhost,1433;TrustServerCertificate=yes", 'SA', 'Passw0rd', { RaiseError => 1 });
#my $dsn = "$driver;Server=$host;OUP-DEV-DEAN\MSSQLSERVER01;initial catalog=MyDirtDB;trusted_connection=yes;TrustServerCertificate=yes;";

package MyDirt::Schema;
use base 'DBIx::Class::Schema';
use DBIx::Class::Schema::Loader qw/ make_schema_at /;
my $schema = make_schema_at(
    'MyDirt::Schema', {
	debug => 1,
	dump_directory => './lib',
    },
    [
        $config->{mssql}->{dbstring},
        $config->{mssql}->{username},
        $config->{mssql}->{password},
        { RaiseError => 1 }
    ]
);
#my $schema = MyDirt::Schema->connect(
use Data::Dumper;
print Dumper MyDirt::Schema;
