#! perl
use warnings;
use strict;
use DBI;
use feature 'say';
use Mojolicious::Lite;
use Mojo::File qw(curfile);
my $conf = curfile->dirname->path('../my_app.json');
my $config = plugin 'JSONConfig' => { file => $conf };
use lib curfile->dirname->sibling('lib')->to_string;
use MyDirt::Schema;

my $orm = MyDirt::Schema->connect(
        $config->{mssql}->{dbstring},
        $config->{mssql}->{username},
        $config->{mssql}->{password},
        { RaiseError => 1 }
);

my $snuffy = $orm->resultset('TblUser')->create({
     userfirstname => 'Airman',
     usermiddlename => 'Onesee',
     userlastname => 'Snuffy',
     useremail => 'airman.snuffy@us.af.mil',
     roleid => 1,
     organizationid => 1,
     rankid => 1
});

my $snuffyAsSubordinate = $orm->resultset('TblSubordinate')->create({
    subfirstname => $snuffy->userfirstname,
    submiddlename => $snuffy->usermiddlename,
    sublastname => $snuffy->userlastname
})->subordinateid;

say $snuffy->userid;

$orm->resultset('TblXrefUserSubordinate')->create({
    userid => $orm->resultset('TblUser')->next(),
    subordinateid => $snuffyAsSubordinate
});
