#! perl
use warnings;
use strict;
use DBI;
use feature 'say';
use Mojolicious::Lite;
use Mojo::File qw(curfile);
my $conf = curfile->dirname->path('../my_dirt.json');
my $config = plugin 'JSONConfig' => { file => $conf };
use lib curfile->dirname->sibling('lib')->to_string;
use MyDirt::Schema;

use Crypt::Passphrase;
use Crypt::Passphrase::Argon2;
my $auth = Crypt::Passphrase->new(
    encoder => Crypt::Passphrase::Argon2->new(
        time_cost => 1
    )
);

my $orm = MyDirt::Schema->connect(
        $config->{mssql}->{dbstring},
        $config->{mssql}->{username},
        $config->{mssql}->{password},
	{ RaiseError => 1, LongReadLen => 4294967295, LongTruncOk => 0 }
);

my $org = $orm->resultset('TblOrg')->find_or_create({
    orgid   => '55200',
    orgname => '552nd ACNS',
});
my @ranks = qw/ AB Amn A1C SrA SSgt TSgt MSgt SMSgt CMSgt /;
push @ranks, ('2d Lt', '1st Lt', 'Capt', 'Maj', 'Lt Col', 'Col', 'Brig Gen', 'Maj Gen', 'Lt Gen', 'Gen');
my $i = 0;
$orm->resultset('TblRank')->find_or_create({ rankid => $i++, ranktype => $_ }) for @ranks;
$orm->resultset('TblRole')->find_or_create({ roleid => 0, roletype => 'big A Airman' });
my $snuffy = $orm->resultset('TblUser')->create({
     userfirstname => 'Airman',
     usermiddlename => 'Onesee',
     userlastname => 'Snuffy',
     useremail => 'airman.snuffy@us.af.mil',
     roleid => 0,
     organizationid => $org,
     rankid => 1
});
my $nuffy = $orm->resultset('TblUser')->create({
     userfirstname => 'Airman',
     usermiddlename => 'Onesee',
     userlastname => 'Nuffy',
     useremail => 'airman.nuffy@us.af.mil',
     roleid => 0,
     organizationid => $org,
     rankid => 3
});
my $users = $orm->resultset('TblUser');
$orm->resultset('TblUserSubordinate')->create({
    userid => $snuffy,
    subordinateid => $nuffy
});
$orm->resultset('TblLogin')->create({
    userid => $snuffy,
    userloginid =>  'Luffy',
    userpassword => $auth->hash_password('baba booey')
});
$orm->resultset('TblLogin')->create({
    userid => $nuffy,
    userloginid =>  'Buffy',
    userpassword => $auth->hash_password('123456')
});

my $dir = curfile->dirname->path('../public/form_templates/');
my @filenames = qw(aetc341 af3070a LOCAR);
my %templates = map {$_, $dir->path("${_}.pdf")->slurp} @filenames;
undef $dir;
undef @filenames;

my $doctypes = $orm->resultset('TblDocType');
my $loc;

$doctypes->find_or_create({
    doctypeid => 682,
    doctypename => 'AETC Form 682',
    doctemplate => $templates{aetc341}
});
$doctypes->find_or_create({
    doctypeid => 174,
    doctypename => 'LOC',
    doctemplate => $templates{LOCAR}
});
$loc = 174;
$doctypes->find_or_create({
    doctypeid => 175,
    doctypename => 'LOA',
    doctemplate => $templates{LOCAR}
});
$doctypes->find_or_create({
    doctypeid => 176,
    doctypename => 'LOR',
    doctemplate => $templates{LOCAR}
});
$doctypes->find_or_create({
    doctypeid => 341,
    doctypename => 'AETC Form 341',
    doctemplate => $templates{aetc341}
});
$doctypes->find_or_create({
    doctypeid => 307,
    doctypename => 'Article 15',
    doctemplate => $templates{af3070a}
});

my $snuffyLOC = $orm->resultset('TblDoc')->create({
    doctypeid => $loc,
    docwhere  => 'Tinker AFB',
    doc       => ''
});
$orm->resultset('TblXrefUserDoc')->create({
    userid => $snuffy,
    docid => $snuffyLOC
});
